### ISSUE TITLE
Enable Issue

### ISSUE THREAD

**Issue by amaclay** [aehrc/redcap_simple_ontology_provider#1]
When downloaded from the redcap external module repo, the directory name is "simple_ontology_provider_vv0.1", which prevented me from enabling it. Changing the name to simple_ontology_provider_v0.1 fixed the issue.

Thank you for writing such a useful module!

**Comment by dconlan** [comment]
Hi, thanks for the report.

It looks like I must have filled something in wrong when I registered the module with REDCap.
This should now be fixed.
