### ISSUE TITLE
Feature request: multiple displays referring to the same code

### ISSUE THREAD

**Issue by lieselotvl** [aehrc/redcap_simple_ontology_provider#2]
Hi,
Would it be possible to allow multiple displays to refer to the same code? 
We use the ICDO-3 codes which are built like this:
CODE     LABEL
8000/0   Neoplasm, benign
8000/0   Tumor, benign
8000/0   Unclassified tumor, benign
8000/1   Neoplasm, uncertain whether benign or malignant
8000/1   Neoplasm, NOS
8000/1   Tumor, NOS
...
Currently, only one of the codes is displayed when searching a label.
Kind regards,
Lieselot

**Comment by dconlan** [comment]
Hi Lieselot,

I will check to see if its possible given the current redcap limitations.

Can you get the icd0 codes out of bioportal? I know there is a snomed ct reference set that maps to icd0 codes, but that doesn't help you much. You could definetly create a FHIR codesystem of the codes and use ontoserver to do the job. 

Dave

**Comment by denshade** [comment]
Hi all,
I've checked it. Sadly REDCap uses a php map as interface. In phpmaps a code can only be used once. 
Specifically:
$map["8000"] = "A" followed by 
$map["8000"] = "B" only keeps the last result:
$map["8000"] == "B" and the old value is overwritten.

The correct way would be to have the REDCap team change the interface to: 
$map["8000"] = ["A", "B"] as having multiple values for the same code is common.

Another quick fix (ugly hack) could be adding spaces after the code: 

    foreach($mresults as $val){
      // make sure result is escaped..
      $code = \REDCap::escapeHtml($val['code']);
      $desc = \REDCap::escapeHtml($val['display']);
     //difference here =>
      while (key_exists($code, $results)){
          $code .= " ";
      }
      //end of difference. <=
      $results[$code] = $desc;
    }

**Comment by dconlan** [comment]
I think if you were doing to use this solution you would need to add the spaces in the input data set when you configured the module. Redcap will store what the display is associated with a code in a cache table. We would need the number of spaces added to be consistent for each entry, or we could get displays changing from when its selected and when its retrieved from the cache.

The way the ontology server works for snomed is a code will have a preferred term and a set of synonyms. If you get a match in a synonym the code is returned, but it will use the preferred term as the display, not the synonym it found the match in. We could implement a similar scheme, maybe taking the first entry for the code as the preferred term, or using the json input and adding a synonym entry.
so
```
[
 {"code" : "8000/0", "display" : "Neoplasm, benign", "synonym": ["Tumor, benign", "Unclassified tumor, benign"] }
 {"code" : "8000/1", "display" : "Neoplasm, uncertain whether benign or malignant", "synonym": ["Neoplasm, NOS", "Tumor, NOS"] }
]
```

**Comment by lawley** [comment]
Hi Lieselot,

Can you elaborate on what you need here?  A code should only have a single
meaning, and this should correspond to the "display" field in the FHIR
CodeSystem.
The other labels are still used when searching for a match, but they're not
normally displayed because these "synonyms" should not convey any different
meaning (which does appear to be the case for your example codes).

michael

**Comment by denshade** [comment]
I believe the problem is that synonyms can't be found as only one code =>
value is stored, which is default behaviour for PHP maps.

**Comment by lieselotvl** [comment]
Hi all,
Thanks for the replies. I think the solution suggested by @dconlan with the preferred term and a set of synonyms would work. The ontology I tried to implement is this one: [http://codes.iarc.fr/codegroup/2](http://codes.iarc.fr/codegroup/2). It seems the perferred term is in bold and the synonyms are below.

**Comment by dconlan** [comment]
Synonym support has been added in v0.5 of the module.
