### ISSUE TITLE
A partial match does not allow to select 'No result found'

### ISSUE THREAD

**Issue by jphilip** [aehrc/redcap_simple_ontology_provider#4]
Hi there,
I am trying to use simple ontology provider to let users select a journal from the sjr listing (for journal quality assessment).
The list has ~30K journals, however it is not inclusive of all journals. If the user is looking for 'American Journal of Indian Education', she enters 'American Journal', a long list of journals appear, however the target journal is not in the list, there is no way for the user to indicate that, for example by selecting 'My journal is not in the list' or whatever label was attributed to No Results found. I do have a second field visible by branching logic to permit free text entry when a journal is not in the list, but it is only made visible if there is no partial match which does not work for journal names since so many of them have common words.
I can think of a workaround with a checkbox saying My journal is not in the list to reveal the free text field, but that is quite cumbersome.
Is there another way to indicate that there is no exact match so that a free text box can be be triggered by ranching logic in that case?
Thanks.

**Comment by dconlan** [comment]
Hi,

You don't need to search by the start of the text, entering 'Indian Education' should shorten the list much quicker than entering "American Journal'. 

I think only the first 20 results are displayed, so we would need to differentiate between not being visible yet and its definetly not on the list. I could add an option to indicate the No Result Found value always be on the list if its not full.

Would that solve the issue?

**Comment by jphilip** [comment]
In this example, 'Indian Education' still brings back several partial matches, none of which is the right one, so it does not help, plus most people would type the beginning of the name. For the not visible yet vs no result at all, if I understand the algorithm, if you type all the words of a journals name, it would be on top of the list thus visible. Even if one word has a typo it should still be on top of the list as it would be very unlikely that 20 journals would have all but one words being the same. To show more than 20 on demand, one would have to implement something like [select2](https://github.com/select2/select2), but that is probably a REDCap issue. 
I don't think it would help to have the No Result Found value always be on the list only if its not full would help because in this example, it is always full if you type words related to journals since it take only one word to get results. If I type 'American Journal of Indian Education', which most people would, I get 20 wrong results, so the No results found would not show.
Maybe the checkbox would be the best way to handle this since it it would always be visible to the user. It would be nice if it could also set the value of the dropdown to No Results thought JS. Not sure if this is possible with Shazam or the new field embedding feature.

**Comment by dconlan** [comment]
I can see what you mean about lots of common words.
Do I need to have a flag to use the old behaviour of just doing a full string match?
Is there some other way to do a sensible search with your data?

The module mostly just replaces the call to bioportal with a local lookup, so it doesn't do anything with the UI, just returns up to 20 search results based on the text typed.

**Comment by jphilip** [comment]
I think as you suggest, it would be a good thing to offer the REDCap admins ways of customizing the search in the form of module options, because there is potentially a wide range of use cases which require different solutions.
One of them could be the number of results returned, another, appending the 'No result' option at the end of the results, and finally a choice of search algorithm.
In that regard, I tried replacing the current version with version 0.2 of the module, on my local REDCap install (with the search on the whole string), and it seems to work better for this use case as long as you have words in the correct order and no typo, otherwise, there are no results. So it could be an option, but I think there are better algorithms out there. 
I found this site which allows comparing different fuzzy string matching algorithms, here is an [example ](https://asecuritysite.com/forensics/simstring?word=amerigan%20journal%20indian%24american%20journal%20of%20indian%20education)for my use case.
Some of those are [implemented in PHP](https://github.com/atomescrochus/laravel-string-similarities) and could be options (The Jaro Winkler algo seems to work good in my case).
I have not done any PHP coding for quite a while, so I don't think I could submit a PR, but if you wanted to create a branch to try some of these algorithms, I could review and test them.

**Comment by jphilip** [comment]
I tried these fuzzy string matching algorithms on my local REDCap installation and they do not seem to work well in this context, plus they are too slow in the PHP implementation. For my use case, the match all string behavior of version 0.2 works best. So having a setting to use the whole string method, or match on individual words would be great and would not break BC. Also an option to add the Not found option at the end of the list when few results are returned would be great too.

**Comment by dconlan** [comment]
ok,
I will add a mechanism to use straight search instead of word based and show the not found option at the end of the list is not full.

I'll try and get it out in the next few days.

**Comment by dconlan** [comment]
I have released version 0.4, adding an option to chose the search type, and the no result entry will show up if there is less than 20 matches.
