### ISSUE TITLE
Request - Config option to switch order of 'code' and 'display'

### ISSUE THREAD

**Issue by 274188A** [aehrc/redcap_simple_ontology_provider#7]
I would love to see the option to control the order of `code` | `display`

some users ask me to have `display` | `code

thanks for this great EM!

**Comment by dconlan** [comment]
Hi,

Is this when the set of values is defined?
So have a new values type of "Bar reversed - display|code"

**Comment by 274188A** [comment]
I use JSON myself - but yes when the user starts searching the text box could have a display option to reverse the code,display order

eg red arrow on pic belows shows desired swap
![image](https://user-images.githubusercontent.com/40014477/132630234-3159e0c7-1a35-423e-b0b2-e3bf621836c5.png)

**Comment by dconlan** [comment]
hmm, ok now I understand the request.

unfortunately the code which creates that label is in DataEntry/ web_service_auto_suggest.php which is redcap code.

So we would need to either
1. Hack the autosuggest functions in javascript.
2. Submit a patch to redcap to get them to change the code.

Here is the relevant code:
```php
foreach ($results as $this_notation=>$this_preflabel) {
		// Prepend notation to preflabel for display purposes
		$this_label = "[$this_notation] $this_preflabel";
		$this_label = filter_tags(label_decode($this_label));
		// Add boldness to search term
		$pos = stripos($this_label, $queryString);
		if ($pos !== false) {
			$this_label = substr($this_label, 0, $pos)
							. "<b style=\"color:#319AFF;\">".substr($this_label, $pos, $queryStringLength)."</b>"
							. substr($this_label, $pos+$queryStringLength);
		}
		// Add to json array
		$json[] = array('value'=>$this_notation, 'label'=>$this_label, 'preflabel'=>$this_preflabel,
						'service'=>$autosuggest_service, 'cat'=>$autosuggest_cat);
	}
```

The line that reads `$this_label = "[$this_notation] $this_preflabel";` would need to change to allow the prefered order.

**Comment by 274188A** [comment]
ok I see - shame but thanks for the answer
